
// Title: LINQ
// Author: Microsoft
// Date: 01-10-2026
// Code version: C# / .NET 10
// Availability: https://learn.microsoft.com/en-us/dotnet/csharp/linq/

using System;
using System.Collections.Generic;
using System.Linq;

namespace FMCGEnterpriseManagementSystem.ViewModels
{
    // View model containing the information required to display
    // the application's dashboard and its financial charts.
    public class DashboardViewModel
    {
        // Number of months displayed on the dashboard.
        // The default value is 12 months.
        public int Months { get; set; } = 12;

        // Collection of monthly income values used by the
        // income chart on the dashboard.
        public List<MonthlyIncome> IncomeByMonth { get; set; } = new();

        // Collection of sales totals grouped by product category.
        // This data is used by the category sales chart.
        public List<CategorySales> SalesByCategory { get; set; } = new();

        // Calculates the total income across all months.
        // LINQ Sum() adds the Income value from each MonthlyIncome record.
        public decimal TotalIncome =>
            IncomeByMonth.Sum(m => m.Income);

        // Calculates the total sales across all product categories.
        public decimal TotalCategorySales =>
            SalesByCategory.Sum(c => c.Sales);

        // Gets the income value from the most recent month.
        // LastOrDefault() returns the last record or null when
        // the collection does not contain any records.
        public decimal ThisMonthIncome =>
            IncomeByMonth.LastOrDefault()?.Income ?? 0;

        // Gets the income value from the month before the current month.
        // The ^2 index accesses the second-last item in the collection.
        // If there is not at least one previous month, zero is returned.
        public decimal LastMonthIncome =>
            IncomeByMonth.Count > 1
                ? IncomeByMonth[^2].Income
                : 0;

        // Calculates the percentage change between the current month
        // and the previous month.
        //
        // Returns null when the previous month's income is zero
        // to prevent a division-by-zero calculation.
        public decimal? MonthOnMonthChange =>
            LastMonthIncome == 0
                ? null
                : (ThisMonthIncome - LastMonthIncome)
                  / LastMonthIncome * 100m;
    }

    // Represents income information for a specific month.
    public class MonthlyIncome
    {
        // Four-digit year associated with the income record.
        public int Year { get; set; }

        // Numeric month value.
        public int Month { get; set; }

        // Display label for the month, such as a formatted month/year.
        public string Label { get; set; } = string.Empty;

        // Total income recorded for the month.
        public decimal Income { get; set; }
    }

    // Represents sales information grouped by product category.
    public class CategorySales
    {
        // Name of the product category.
        public string Category { get; set; } = string.Empty;

        // Total sales generated by the category.
        public decimal Sales { get; set; }
    }
}
