//  Title: Classes and Objects - C# Programming Guide
//    Author: Microsoft
//    Date: 2026
//    Code version: C#
//    Availability: https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/types/classes

namespace FMCGEnterpriseManagementSystem.ViewModels.Reports
{
    // ViewModel used to transfer product sales information to the item sales report.
    public class ItemSalesReportViewModel
    {
        // Stores the unique identifier of the product.
        public int ProductId { get; set; }

        // Stores the product code displayed in the report.
        public string ProductCode { get; set; } = string.Empty;

        // Stores the product name displayed in the report.
        public string ProductName { get; set; } = string.Empty;

        // Stores the total quantity of the product sold.
        public int QuantitySold { get; set; }

        // Stores the total sales value generated by the product.
        public decimal TotalSales { get; set; }
    }
}