// Title: ASP.NET Core MVC View Models
// Author: Microsoft
// Date: 04-10-2026
// Code version: C# / .NET 10
// Availability: https://learn.microsoft.com/en-us/aspnet/core/mvc/views/overview

namespace FMCGEnterpriseManagementSystem.ViewModels.Reports
{
    // View model containing sales performance information for a sales representative.
    public class SalesRepReportViewModel
    {
        // Unique identifier of the sales representative.
        public int SalesRepresentativeId { get; set; }

        // Code used to identify the sales representative.
        public string SalesRepCode { get; set; } = string.Empty;

        // Name of the employee assigned to the sales representative.
        public string EmployeeName { get; set; } = string.Empty;

        // Area assigned to the sales representative.
        public string Area { get; set; } = string.Empty;

        // Sales target assigned to the representative.
        public decimal SalesTarget { get; set; }

        // Total sales generated by the representative.
        public decimal TotalSales { get; set; }

        // Commission percentage assigned to the representative.
        public decimal CommissionRate { get; set; }

        // Estimated commission calculated from the representative's sales.
        public decimal EstimatedCommission { get; set; }
    }
}


