// Title: Entity Framework Core - Entity Properties
// Author: Microsoft
// Date: 12-01-2023
// Code version: Entity Framework Core
// Availability: https://learn.microsoft.com/en-us/ef/core/modeling/entity-properties
//
using System;

namespace FMCGEnterpriseManagementSystem.Models
{
    // Represents a notification generated by the application.
    public class Notification
    {
        // Primary key that uniquely identifies the notification.
        public int NotificationId { get; set; }

        // Identifies the category of notification being generated.
        public NotificationType Type { get; set; }

        // Stores the notification heading displayed to the user.
        public string Title { get; set; }

        // Stores the detailed notification message.
        public string Message { get; set; }

        // Indicates whether the notification has been viewed by the user.
        public bool IsRead { get; set; }

        // Indicates whether an email notification has already been sent.
        public bool EmailSent { get; set; }

        // Records when the notification was created.
        public DateTime CreatedDate { get; set; } = DateTime.Now;

        // Optional identifier of the record that caused the notification.
        public int? RelatedEntityId { get; set; }

        // Stores the type of record that caused the notification,
        // such as an invoice, quote, or product.
        public string RelatedEntityType { get; set; }
    }
}